<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoThrive.Core\CargoThrive.Core.csproj" />
    <ProjectReference Include="..\CargoThrive\CargoThrive.API.csproj" />
  </ItemGroup>

</Project>
