<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath></BaseOutputPath>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>Properties/CargoThrive.API.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\CargoThrive.API.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\CargoThrive.API.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoThrive.Core\CargoThrive.Core.csproj" />
    <ProjectReference Include="..\CargoThrive.Infrastructure\CargoThrive.Infrastructure.csproj" />
  </ItemGroup>

</Project>
