// <auto-generated />
using System;
using CargoThrive.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoThrive.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104033907_RoleAll")]
    partial class RoleAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoThrive.Core.Models.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FailReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LoginStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("UserManagementId")
                        .HasColumnType("bigint")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("UserManagementId");

                    b.ToTable("LoginLog", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("描述");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("父权限ID（0表示顶级权限）");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("菜单URL或接口地址（按钮权限可为空）");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer")
                        .HasComment("权限类型（0=菜单，1=按钮，2=接口）");

                    b.Property<int>("Sort")
                        .HasColumnType("integer")
                        .HasComment("排序）");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("角色功能说明");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("角色名称（同一租户内不重复）");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("租户外键（0=系统用户，关联系统级角色）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasComment("权限外键");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色外键");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermission_Role_Permission");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("租户名称");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.TestModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Test", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserManagement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("用户登录标识，支持手机号/邮箱格式");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("EndTime")
                        .HasColumnType("text")
                        .HasComment("格式为HH:mm，如18:00，非必填项");

                    b.Property<DateTime?>("LastPasswordErrorTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("密码错误时更新为当前时间，成功登录或错误次数重置时可设为null，非必填项");

                    b.Property<int?>("LoginCountTimeLimit")
                        .HasColumnType("integer")
                        .HasComment("例如：30表示30分钟内限制登录次数，为空表示无时间范围限制，非必填项");

                    b.Property<int>("PasswordErrorCount")
                        .HasColumnType("integer")
                        .HasComment("初始值为0，输错时递增，成功登录时重置为0，非必填（默认0）");

                    b.Property<DateTime?>("PasswordErrorLockEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("冷却期内禁止登录，冷却结束后可重新尝试；成功登录时重置为null");

                    b.Property<DateTime?>("PasswordExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("格式为DateTime，为空表示密码永不过期，非必填项");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("密码哈希值，禁止明文存储");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("密码盐值");

                    b.Property<string>("StartTime")
                        .HasColumnType("text")
                        .HasComment("格式为HH:mm，如09:00，非必填项");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("租户外键（0=系统管理员，关联总管理员）");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("用户在系统中显示的真实姓名");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("UserManagement", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserManagementSign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Country")
                        .HasColumnType("integer")
                        .HasComment("管理员所属国家/地区（关联CountryEnum枚举）");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("ShowNickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("管理员签名的显示名称");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasComment("管理员签名（用于身份标识或文件签署）");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<long>("UserManagementId")
                        .HasColumnType("bigint")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("UserManagementId", "Status")
                        .HasDatabaseName("IX_UserManagementSign_User_Status");

                    b.ToTable("UserManagementSign", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("实体主键 ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色外键");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasComment("状态（1启用true，0禁用false）");

                    b.Property<long>("UserManagementId")
                        .HasColumnType("bigint")
                        .HasComment("用户外键");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRole_RoleId");

                    b.HasIndex("UserManagementId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRole_User_Role");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRole_RoleId");

                    b.HasIndex(new[] { "UserManagementId", "RoleId" }, "IX_UserRole_User_Role")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("CargoThrive.Core.Models.LoginLog", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.UserManagement", "UserManagement")
                        .WithMany()
                        .HasForeignKey("UserManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserManagement");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.Permission", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.Permission", "ParentPermission")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPermission");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.Role", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.RolePermission", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoThrive.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserManagement", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserManagementSign", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.UserManagement", "UserManagement")
                        .WithMany()
                        .HasForeignKey("UserManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserManagement");
                });

            modelBuilder.Entity("CargoThrive.Core.Models.UserRole", b =>
                {
                    b.HasOne("CargoThrive.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoThrive.Core.Models.UserManagement", "UserManagement")
                        .WithMany()
                        .HasForeignKey("UserManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
